### ISSUE TITLE
Handbrake Nvenc not working

### ISSUE THREAD

**Issue by st1905** [shkhln/revird-aidivn#1]
`# HandBrakeCLI --help | grep -A12 "Select video encoder"
Cannot load libnvidia-encode.so.1
[18:42:25] hb_init: starting libhb thread
[18:42:25] thread 803fb5500 started ("libhb")
   -e, --encoder <string>  Select video encoder:
                               x264
                               x264_10bit
                               x265
                               x265_10bit
                               x265_12bit
                               mpeg4
                               mpeg2
                               VP8
                               VP9
                               theora
       --encoder-preset <string>
                           Adjust video encoding settings for a particular`

Is there a possibility to load libnvidia-encode.so.1 using libc6-shim ?

**Comment by shkhln** [comment]
> Is there a possibility to load libnvidia-encode.so.1 using libc6-shim ?

`./bin/nv-sglrun ghb`

**Comment by st1905** [comment]
It worked, thank you.
