### ISSUE TITLE
Similar patch of multimedia ports to use for ideas

### ISSUE THREAD

**Issue by scfarley** [shkhln/revird-aidivn#2]
I noticed this repo after I had already made my own changes to ports to support `shkhln/libc6-shim`.  It figures.  :smile:  Anyway, here are my changes.  Some of which I *think* require less changes to configure them.  https://github.com/scfarley/ports/commit/42b8875ea435c0fb4ff8a1d9db8797f6fa25be37  I named the FFmpeg headers port `ffnvcodec` to better match what is installed.

Thank you very much for `libc6-shim` and `linuxulator-steam-utils`.  The latter is nice for running the Linux version of Firefox.

**Comment by shkhln** [comment]
That's curious. Afaik, nvenc doesn't work at all without the patch for x11/nvidia-driver from this repo, so I didn't really expect anyone to miss this additional stuff. In any case, I'm not going to submit these changes myself (I doubt danfe@ wants to be stuck with a potentially high-maintenance patch), so whatever you are doing with ports is not my concern.

**Comment by scfarley** [comment]
I am using your patch to `x11/nvidia-driver` primarily to get ahead of the last nvidia security issue.  I was not thinking about nvenc at that moment.  I had started from https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=249505 but had gone straight to the nvidia update and missed your port updates to multimedia.

No problem.  I will probably submit some port updates after 249505 lands.  It may be awhile before it does, but I am fairly busy with other ports and a code review at the moment.  Since these are not useful for this repo, I will close the issue.

**Comment by shkhln** [comment]
Now that [495.29.05](https://forums.developer.nvidia.com/t/linux-solaris-and-freebsd-driver-495-29-05-beta/192073) exists (with the relevant kernel parts implemented upstream) do you plan to submit nvenc changes or should I do this myself?

**Comment by scfarley** [comment]
I do not mind submitting patches for ports to support `nvenc` in the newer driver, but I may wait until after this driver, or later, hits the ports tree before submitting them.  In the meantime, I can verify that patches still work as I have not checked for awhile.

Although quite happy the support is there in the driver, it would have been helpful if Nvidia had mentioned it in the release notes.  :smiley:
